package main

//go:generate go run . gen-docs

import (
	"bytes"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// docsPath is the generated command reference. Cobra's doc generator walks the
// live command tree, so the docs are the single source of truth by construction
// — adding a command or flag updates them with no hand edits. Kept in lockstep
// via `go generate` + a pre-commit --check guard.
const docsPath = "COMMANDS.md"

// renderDocs renders the whole command tree to a single markdown document.
func renderDocs() (string, error) {
	root := rootCmd()
	root.DisableAutoGenTag = true // no timestamp line → stable output for --check

	var b bytes.Buffer
	b.WriteString("<!-- generated by `wf gen-docs` — do not edit; run `go generate ./...` -->\n\n")

	// GenMarkdownTree writes one file per command; we instead concatenate the
	// tree into a single file by walking it depth-first.
	var walk func(c *cobra.Command) error
	walk = func(c *cobra.Command) error {
		if c.Hidden {
			return nil
		}
		if err := doc.GenMarkdownCustom(c, &b, func(s string) string { return s }); err != nil {
			return err
		}
		for _, sub := range c.Commands() {
			if err := walk(sub); err != nil {
				return err
			}
		}
		return nil
	}
	if err := walk(root); err != nil {
		return "", err
	}
	return b.String(), nil
}

// genDocsCmd is a hidden command that writes (or, with --check, verifies) the docs.
func genDocsCmd() *cobra.Command {
	var check bool
	c := &cobra.Command{
		Use:    "gen-docs",
		Short:  "generate COMMANDS.md from the command tree",
		Hidden: true,
		Args:   cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			want, err := renderDocs()
			if err != nil {
				return err
			}
			if check {
				got, err := os.ReadFile(docsPath)
				if err != nil || string(got) != want {
					return fmt.Errorf("%s is stale; run `go generate ./...` and commit", docsPath)
				}
				return nil
			}
			if err := os.WriteFile(docsPath, []byte(want), 0o644); err != nil {
				return err
			}
			fmt.Printf("wrote %s\n", docsPath)
			return nil
		},
	}
	c.Flags().BoolVar(&check, "check", false, "fail if COMMANDS.md is out of date")
	return c
}
