package main

//go:generate go run . gen-docs

import (
	"fmt"
	"os"
	"strings"
)

// docsPath is the generated command reference, rendered from the command table.
// It sits next to the source so `go generate` keeps it in lockstep with the CLI.
const docsPath = "COMMANDS.md"

// renderDocs builds the markdown command reference from the same command table
// that drives dispatch and `--help`, so the three can never disagree.
func renderDocs() string {
	var b strings.Builder
	b.WriteString("<!-- generated by `wf gen-docs` — do not edit; run `go generate ./...` -->\n")
	b.WriteString("# wf commands\n\n")
	b.WriteString("Workflow manager. Full `--help` output, rendered from the command table.\n\n")
	b.WriteString("```\n")
	b.WriteString(renderUsage() + "\n")
	b.WriteString("```\n")
	return b.String()
}

// cmdGenDocs writes the generated docs and, with --check, fails if they are stale.
func cmdGenDocs(args []string) error {
	check := false
	for _, a := range args {
		if a == "--check" {
			check = true
		} else {
			return fmt.Errorf("gen-docs: unknown argument: %s", a)
		}
	}

	want := renderDocs()
	if check {
		got, err := os.ReadFile(docsPath)
		if err != nil || string(got) != want {
			return fmt.Errorf("%s is stale; run `go generate ./...` and commit", docsPath)
		}
		return nil
	}
	if err := os.WriteFile(docsPath, []byte(want), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", docsPath)
	return nil
}
